workspace:
  base: /go
  path: src/go.jonnrb.io/radarsign

pipeline:
  build:
    image: golang:latest
    commands:
      - go get -t ./...
      - go test -v ./...
      - go build ./...
  docker:
    image: plugins/docker
    repo: jonnrb/radarsign
    storage_driver: overlay2
    secrets: [ docker_username, docker_password ]
