kind: pipeline
name: default

workspace:
  base: /go
  path: src/go.jonnrb.io/radarsign

steps:
- name: build
  image: golang:latest
  commands:
  - go get -t ./...
  - go test -v ./...
  - go build ./...
- name: docker
  image: plugins/docker
  settings:
    repo: jonnrb/radarsign
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
