---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:latest
  commands:
  - go get -t ./...
  - go test -v ./...
  - go build ./...

- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: jonnrb/radarsign
    username:
      from_secret: docker_username

...
